FROM alpine:3.12.0
ENV TZ="Europe/Zurich"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# setup SMB server
RUN apk add --no-cache --update \
    python3 docker docker-compose \
    py3-pip \
    && pip3 install requests

COPY worker/ /opt/worker

# set entry services
CMD python3 /opt/worker/main.py